---
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/google/keep-sorted
    rev: v0.6.1
    hooks:
      - id: keep-sorted
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.4.0
    hooks:
      - id: golangci-lint
